hamlet-io/docs

README.md

This PR updates the default docusaurus readme to include the outline for the basic process for forking the repo, creating a branch and then creating a PR from the fork/branch into master.
This PR is also to test the "Now" implementation.

Feature - Update Readme

---

README.md
docs/tutorials/create/multi/hello-hamlet.md
package-lock.json
package.json
src/css/custom.css
src/theme/Mermaid.js

This PR implements Mermaid into the Markdown files https://mermaidjs.github.io/#/
Currently a small workaround is required to get this setup in v2 docusaurus. This can be replaced later when its officially supported.
In order to use Mermaid within a .md file, you must first import the plugin at the top of the file:
```import Mermaid from '@theme/Mermaid';```
you can then use the provided React objects to create Mermaid diagrams within the file.
```
<Mermaid chart={`
classDiagram
Animal <|-- Duck
Animal <|-- Fish
Animal <|-- Zebra
Animal : +int age
Animal : +String gender
Animal: +isMammal()
Animal: +mate()
class Duck{
+String beakColor
+swim()
+quack()
}
class Fish{
-int sizeInFeet
-canEat()
}
class Zebra{
+bool is_wild
+run()
}
`}/>
```
Note: existing mermaid references have been …

Feature Mermaid Markdown

---

README.md
static/examples/README.md

As per discussions in #6 - this PR creates a directory to house CMDB examples. The intention is that the CMDB content will be generated by the hamlet code repository itself during build, and commit any necessary updates into this directory of the docs site. The docs can then reference the structure and content within, knowing it will remain up-to-date with hamlet.

Feature - Examples Directory

---

docs/getting-started/getting-started-01.md
docs/getting-started/getting-started-02.md
docs/getting-started/getting-started-05.md
docs/tutorials/create/multi/hello-hamlet.md
docusaurus.config.js

Contributes to #21 
Deploying after #22 has really tidied up the broken-link-checker, and revealed only a few more broken links. This PR resolves those.

Fix - More Broken Urls

---

docs/tutorials/create/multi/hello-hamlet.md

resolved guide pointing to non-existent docker container registry

Fix - Guide URL

---

docs/reference/cmdb/anatomy.md
docs/reference/cmdb/schemas.md
sidebars.js

Small documentation update to explain purpose of CMDB component-specific settings files.
updated solution schema with typical structure of tiers object.
Added example for apigw file.
Renamed the two seperate cmdb reference files into "anatomy" and "schemas". Anatomy deals with the CMDB directory structure whereas "schemas" handles the contents of it.

Documentation - Component Specific Settings Files in CMDB

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This PR introduces Github templates for Issues and PR's. This PR is an example of the PR template.

New Feature - Issue and PR Templates (Docs site specific)

---

docs/design-concepts/linking.md
sidebars.js

Document links and link behaviour to allow hamlet end-users implement them successfully in their CMDBs.

Feature - Documentation - Links

---

README.md
docs/releases/schedule.md
docusaurus.config.js
package-lock.json
package.json

Updated to docusaurus v alpha 48 and updated navbar to include a dropdown for Release info
Closes #8

Feature navbar dropdown

---

.gitignore
package-lock.json
package.json
sidebars.js
src/pages/reference.js

Initial Commit for a new page that renders all component references based on a published hamlet schema.
Contributes to #15

Reference page for Component References

---

src/pages/reference.js
src/pages/styles.module.css

feat: formatted properties into table

---

docs/releases/schedule.md

Align to commit convention. Clarify a few points.

refactor: Revise release strategy

---

src/components/HamletJsonSchema/index.js

- Point the schema loader function at the now-deployed demo schemas.
- Refactor schema loader function to allow it to load different paths and versions.

Feature - Production Schema Paths

---

package-lock.json

Update - NPM Module Update

---

src/components/HamletComponents/index.js
src/components/HamletExample/index.js

Separates out an example labels from the rest of the props, allowing simpler defining of the labels. Corrects a problem with labels that caused duplication.

Fix - Labels on Examples

---

package-lock.json
package.json
src/pages/index.js

Upgraded docusaurus version.
- Resolved breaking change of replacing `classnames` npm module with clsx.

Alpha 58 Update

---

blog/2020-07-07-hamlet-network-component.md

Blog article exploring the network component in depth.

docs(blog): network deepdive

---

.github/workflows/update-schemas

Creates the MVP of a Github Action for the deployment of Hamlet Schemas
* Uses a Hamlet container to generate the schemas and publish them into this project
* This Action implements a ["modularised" Action ](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action)published in the [hamlet-io org](https://github.com/hamlet-io/github-action-hamlet), which simplifies performing Hamlet tasks in a Github Action
* Initially this Action is only triggered manually/on the update of master - it is mostly intended to implement and test out the above "modular" Action
* Docs to the new action are in the repo readme, with intended updates to the hamlet.io documentation if/when the Action is more fleshed out with features.
* This Action publishes the …

Feat -Github Action for Schema Updates

---

docs/foundations/anatomy.md
docs/hello/welcome.md

* Update the `Anatomy of a CMDB` documentation.
* Corrects a broken link to our first guide.

Docs - CMDB Anatomy

---

docs/foundations/links.md

Revisited the Links documentation.

Docs - Links

---

README.md
package-lock.json
src/pages/index.js

Fix get started link on home page and updates formatting of readme file
Fixes link on index page

Fix home link

---

docs/hello/hamlet.md

Updates to the hello hamlet docs to follow a better flow, didn't actually add much new content just reviewed what was already there and tweaked it

refactor: rework the hello hamlet content

---

docusaurus.config.js

Broken links have previously been addressed.
As per (Closes #73) we want to now maintain
a consistent state of working links. This will
now cause a build to fail whilst broken links
remain.

chore: thow builds on broken links

---

blog/2021-02-10-spas-with-github-authentication-made-easy.md
blog/2021-02-10-static-sites-with-github-authentication-made-easy.md

blog article on implementing cfcognito and githubidp modules

docs: blog article on implementing cfcognito and githubidp modules

---

docs/learn/layers/account.md
docs/learn/layers/blueprint.md
docs/learn/layers/intro.md
docs/learn/layers/product.md
docs/learn/layers/tenant.md

Updates the Tenant, Account and Product Learn docs to reflect the recent overhauls of the CLI.
Current CLI arguments were invalid/unnecessary, the prompts look different and there is fewer of them, and there is no final revision prompt or output now.
Also a small number of changes to the defaults have occurred that were previously covered in the guides that required amendment or removal.
locally running commands in guide

Docs: Revision of Hamlet Learn post-CLI overhaul

---

blog/2020-06-01-azure-plugin-breakdowns-p2.md
blog/2020-07-07-hamlet-network-component.md
blog/2021-02-10-static-sites-with-github-authentication-made-easy.md
blog/2021-02-26-diagram-plugin.md

Align with the cli changes introduced in https://github.com/hamlet-io/executor-python/pull/89
Testing broken 
Will use CI Testing

fix: update commands to align with cli updates

---

.github/workflows/node.js.yml
package-lock.json
package.json

Updates docusaurus framework
Incl. update to build pipeline to use nodejs v 14.6.0 as the default is 10.x which is now incompatible
Staying up-to-date
Local build and serve

chore: update framework to alpha-72

---

src/components/HamletJsonSchema/index.js

Document the new `attributesets` that have been added to Hamlet Deploy recently.
Provide full documentation of the possible Solution structure.
Locally - the new `attributesets` are available in the menu at https://localhost:3000/reference and all load as intended

docs: adds the latest attributesets to the JSONSchema data tables

---

src/components/HamletJsonSchema/index.js

Adds the apigateway into the schema list. Was imported but not included in the schema list
Couldn't find the schema 
- None
- None
- None

fix: include apigateway in schema

---

blog/2021-05-13-Release-v8.1.md

Adds release blog for the hamlet 8.1 release to outline what's been added to hamlet overall
Show off what we've done 
- None
- None
- None

docs: 8.1 release notes

---

blog/2021-05-13-Release-v8.1.md

Update change log links to use the right tag value 
Links were broken and heading to the wrong palce
Tested locally 
- None
- None
- None

fix: links for change log notes

---

blog/2021-01-13-template-deploys.md
blog/2021-02-10-static-sites-with-github-authentication-made-easy.md
docs/foundations/links.md

The query command has been replaced and is no longer used so we need to update the docs to align
Align with latest changes in hamlet
tested locally
- None
- None
- None

feat: update docs to remove query command

---

blog/2021-09-18-Release-v8.3.md
docs/getting-started/install.md

Outlines the changes made to hamlet and its support services for the 8.3 hamlet release
To show what has been done and to get people interested in what we have been doing 
- None
- None
- None

feat: add 8.3 release notes blog post

---

blog/2021-05-13-Release-v8.1.md
blog/2021-09-18-Release-v8.3.md
docs/getting-started/aws-serverless/build-app/create-app-image.md
docs/getting-started/aws-serverless/build-app/deploy-app-image.md
docs/getting-started/aws-serverless/deploy-container/hamlet-hello-api.md
docs/getting-started/aws-serverless/deploy-container/loadbalancer-deployment.md
docs/getting-started/install.md
docs/reference/software/python_executor/cli.md

- Remove the use of instances within the getting started snippets
- Use the Type attribute instead of the root object id
- Remove anything that isn't covered in the guide
- Update references from hamlet-cli to hamlet for the hamlet cli 
- Remove references to dos2unix 
The newer type format makes it easier to follow how a solution should be put together and removes some of the complexity in setting up components
Tested locally 
- None
- None
- None

refactor(gettingstarted): update solution format

---

src/components/HamletJsonSchema/index.js

Minor fix to align with component rename for efs to fileshare
Website deployment was failing
Tested locally
- None
- None
- None

fix(schema): rename efs to fileshare

---

package-lock.json
package.json

- Updates to the latest version of docusaurus
- Security patches
Keeping up to date and ensuring security issues are fixed up
- None
- None
- None

chore: update packages for docusarus

---

.github/workflows/update-schemas.yml
package-lock.json
package.json

- Updates packages to latest versions
- Adds a deployment tracker to schema updates
Keeps our site up to date 
The deployment definition on the schema updates allows us to monitor that the process is working
- None
- None
- None

chore: package updates and deployment tracking

---

src/components/DataTables/index.js
src/components/HamletJsonSchema/index.js
src/pages/reference/index.js
static/schema/latest/AttributeSet-schema.json
static/schema/latest/Blueprint-schema.json
static/schema/latest/Component-schema.json
static/schema/latest/Entrance-schema.json
static/schema/latest/Layer-schema.json
static/schema/latest/Module-schema.json
static/schema/latest/Reference-schema.json
static/schema/latest/Task-schema.json

- Adds support for linking to attribute sets and components
- Updates naming of link based table references to use the name of the thing being referenced
- Adds the base level schema description to the reference page
- Adds the task schema as this can now be accessed by users
Makes the documentation easier to follow and provides more contextual information to the user
Tested locally
- None
- None
- None

feat(reference): link naming in tables and descriptions

---

blog/2021-12-16-Release-v8.4.md

- Adds a blog post for the 8.4 release of hamlet
Show off what we did in this release
- None
- None
- None

feat: 8.4 release post

---

docs/getting-started/aws-serverless/build-app/build-locally.md
docs/getting-started/aws-serverless/deploy-baseline/account-bootstrap.md
docs/getting-started/aws-serverless/deploy-baseline/environment-bootstrap.md
docs/getting-started/aws-serverless/deploy-container/configure-api.md
docs/getting-started/install.md

- Updates the getting started guide to use solution level settings instead of name spaces to make it easier to follow
This is a simpler approach and aligns with the use case for using the solution level settings over setting namespaces
Tested locally
- None
- None
- None

refactor: getting started guide settings

---

package-lock.json
package.json
src/components/DataTables/index.js
src/components/DataTables/styles.css
src/pages/reference/index.js

Some updates to the reference table layout to show that the values are different options rather than the string , is part of the settings
Hopefully makes it easier to understand how the values can be used
Tested locally
- None
- None
- None

refactor: refererence table

---

.github/workflows/node.js.yml
docs/how-to/configure/provider-authentication.md
docusaurus.config.js
package-lock.json
package.json
src/components/DataTables/index.js

- Updates npm packages to latest versions
- removes unused packages from react components
- Fix missing HAMLET in auth config
- Add edit button to all pages
Keeping up with appearances and minor bug fixes
Tested locally 
- None
- None
- None

chore: package updates and cleanup

---

docs/getting-started/create-cmdb.md
docs/getting-started/index.md
docs/getting-started/install.md

This merge uplifts some of the getting started documentation to reflect the current user experience as of hamlet version 9.14.3. Some minor grammatical / syntactic tweaks are also included.
To ensure accuracy of the documentation, provide clarity and a smoother experience for new users.
The changes in the documentation are largely specific to observed drift between the documentation and the new user experience.
- None
- None
- None

docs: updates getting-started docs for version 9.14.3

---

blog/2022-03-25-Release-8.5.md
docs/getting-started/install.md

- Adds the blog post for the 8.5 hamlet engine release
- Updates the install guide to remove the need for Java
Shows off what we've done in this release
- None
- None
- None

feat: add blog post for 8.5 release of the engine

---

package-lock.json
package.json

- Security fixes and updates to docusaurus
Just keeping up with the times
- None
- None
- None

chore: update node packages to latest versions

---

blog/2022-08-24-Release-8.7.md
package-lock.json
package.json

- Adds the release blog post for 8.7
- Updates docusaurus to latest version
Update the world on what we've been up to
Docusaurus v2 is now GA
Tested locally
- None
- None
- None

feat: add release blog and update packages

---

package-lock.json
package.json

- Fix security issues and add updates from docs updates
Keep up to date.
- None
- None
- None

chore: update website packages

---

blog/2022-10-14-Release-8.8.md

Add blog post for 8.8 release of hamlet
Show off what we've done.
- None
- None
- None

feat: add release 8.8 blog post

---

.github/workflows/static.yml
package.json
yarn.lock

- start will run the server rather than creating the production build
CI pipeline would hang and never run 
Tested locally
- None
- None
- None

fix: run build instead of start in ci

---

search/crawler/Dockerfile

fix permissions issue when installing packages for crawler
docker build was failing
Tested locally
- None
- None
- None

fix: dockerfile build for crawler

---

blog/2023-06-16-Release-8.9.md
package.json
yarn.lock

Add blog post for 8.9 release of hamlet 
Show off what we've done
- None
- None
- None

feat: 8.9 release

---

blog/2023-09-29-Release-9.0.md

Adds blog post for the 9.0 release of the engine
Show what we have done and what has changed
- None
- None
- None

feat: add 9.0 blog release post
